# Generated by Django 4.1.7 on 2023-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0003_remove_investimento_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='investimento',
            field=models.TextField(max_length=20),
        ),
    ]
